import PDFDocument from 'pdfkit';
import { IInvoice } from '../models/Invoice';
import { IAgency } from '../models/Agency';

export function generateInvoicePDF(invoice: IInvoice, agency: IAgency): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(24).fillColor('#1a56db').text('INVOICE', 50, 50);
    doc.fontSize(10).fillColor('#374151');
    doc.text(agency.name, 50, 85);
    doc.text(agency.address, 50, 100);
    doc.text(agency.email, 50, 115);

    // Invoice meta
    doc.text(`Invoice #: ${invoice.invoiceNumber}`, 400, 85);
    doc.text(`Date: ${new Date(invoice.issuedAt).toLocaleDateString()}`, 400, 100);
    if (invoice.dueDate) {
      doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, 400, 115);
    }
    doc.text(`Status: ${invoice.status.toUpperCase()}`, 400, 130);

    // Divider
    doc.moveTo(50, 155).lineTo(545, 155).strokeColor('#e5e7eb').stroke();

    // Line items header
    doc.fontSize(9).fillColor('#6b7280');
    doc.text('DESCRIPTION', 50, 170);
    doc.text('QTY', 340, 170);
    doc.text('UNIT PRICE', 390, 170);
    doc.text('TOTAL', 490, 170);

    doc.moveTo(50, 185).lineTo(545, 185).strokeColor('#e5e7eb').stroke();

    // Line items
    let y = 195;
    doc.fontSize(10).fillColor('#111827');
    invoice.lineItems.forEach((item) => {
      doc.text(item.description, 50, y, { width: 280 });
      doc.text(String(item.quantity), 340, y);
      doc.text(`${invoice.currency} ${item.unitPrice.toFixed(2)}`, 390, y);
      doc.text(`${invoice.currency} ${item.total.toFixed(2)}`, 490, y);
      y += 25;
    });

    // Totals
    doc.moveTo(350, y + 5).lineTo(545, y + 5).strokeColor('#e5e7eb').stroke();
    y += 15;
    doc.fontSize(10).fillColor('#374151');
    doc.text('Subtotal:', 390, y);
    doc.text(`${invoice.currency} ${invoice.subtotal.toFixed(2)}`, 490, y);
    y += 18;
    if (invoice.discount > 0) {
      doc.text('Discount:', 390, y);
      doc.text(`-${invoice.currency} ${invoice.discount.toFixed(2)}`, 490, y);
      y += 18;
    }
    if (invoice.tax > 0) {
      doc.text(`Tax (${invoice.taxRate}%):`, 390, y);
      doc.text(`${invoice.currency} ${invoice.tax.toFixed(2)}`, 490, y);
      y += 18;
    }
    doc.fontSize(12).fillColor('#111827').font('Helvetica-Bold');
    doc.text('Total:', 390, y);
    doc.text(`${invoice.currency} ${invoice.totalAmount.toFixed(2)}`, 490, y);
    y += 18;
    doc.fontSize(10).fillColor('#059669').font('Helvetica');
    doc.text('Amount Paid:', 390, y);
    doc.text(`${invoice.currency} ${invoice.amountPaid.toFixed(2)}`, 490, y);
    y += 18;
    doc.fillColor('#dc2626');
    doc.text('Balance Due:', 390, y);
    doc.text(`${invoice.currency} ${invoice.outstandingBalance.toFixed(2)}`, 490, y);

    // Notes
    if (invoice.notes) {
      y += 40;
      doc.fontSize(9).fillColor('#6b7280').text('Notes:', 50, y);
      doc.text(invoice.notes, 50, y + 14, { width: 495 });
    }

    // Footer
    doc.fontSize(8).fillColor('#9ca3af').text('Generated by TourOps', 50, 760, { align: 'center', width: 495 });

    doc.end();
  });
}
